name: Telegram Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          curl -X POST \
          "https://api.telegram.org/bot8947745976:AAFcrmvT4en1A3zJZBcMjgcbsfYklyELu4U/sendMessage" \
          -d chat_id="1778604935" \
          -d text="✅ TEST tiesiogiai be GitHub Secret"
